# Generated by Django 4.2.2 on 2023-07-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Staff',
        ),
    ]
