# Generated by Django 4.2.2 on 2023-07-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(default=1),
        ),
    ]
