# Generated by Django 4.2.2 on 2023-07-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
