# Generated by Django 4.2.2 on 2023-07-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_staff_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
    ]
