# Generated by Django 4.2.2 on 2023-08-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_delete_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profileimg',
            field=models.ImageField(default='default-profile-pic.jpg', upload_to='profile_images'),
        ),
    ]
