# Generated by Django 4.2.2 on 2023-08-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_staff_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsissuance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.assets'),
        ),
    ]
